### ISSUE TITLE
As a user I would like a dedicated search experience

### ISSUE THREAD

**Issue by longhotsummer** [laws-africa/constitution-app-react#4]
We want to mimic the Wikipedia apps search experience (as it works on iOS), namely:

* a dedicated search button an the bottom
* tapping on search takes the user to a page dedicated to search (see screenshot)
* search page has search bar at top
* same experience searching as we have today (faceted search)

Possibly later:

* store search history locally
* list recent searches on search page
* tapping on recent search mimics typing it into search box

# Tasks

* [x] add new search tab (this will make the tab bar to crowded, but soon we will remove one of the other tabs)
* [x] search tab view has Search heading at top, and search bar beneath that
* [x] move logic for doing actual search into search view (out of homepage view) -- actual search logic remains the same for now
* [ ] (to be discussed) when tapping in the search box on the homepage, jump to the search tab and activate the search box, so the user is typing in there instead

![IMG_0007](https://user-images.githubusercontent.com/4178542/98641531-96310a80-2334-11eb-8d7f-2e87a2a30101.PNG)
